### PR TITLE
Kwalitee score improvements

### PR DESCRIPTION
**Pull request by gryphonshafer**
I'm participating in the CPAN Pull Request initiative (http://cpan-prc.org), and I was assigned your module for March. After having reviewed it, I wasn't really sure what I could to do help improve it. So I made some tiny changes to raise the Kwalitee score. I've run the test suite and a few test scripts, and I don't think I've broken anything. I hope this was at least slightly helpful.

### CODE REVIEW

**Comment by ironcamel** [comment]
Thanks for this @gryphonshafer . Sorry for taking so long to respond. I will merge this PR as soon as I get a chance to sanity check all of your changes. Thanks!

**Comment by mjg17** [comment]
These changes look sane to me.
Cheers
Michael

**Comment by ironcamel** [comment]
I would like to merge this, but github is saying this branch has conflicts that must be resolved.

**Comment by gryphonshafer** [comment]
I'd love to help, but I'm too over-allocated. Given how much time has passed, it's probably better to just drop the PR.

**Pull request closed without merging**
